version: '3.0'

services:
  frontend:
    image: teodossidossev/mse2024-ui:latest
    container_name: frontend
    ports:
      - "8888:8888"
    depends_on:
      - backend

  backend:
    image: teodossidossev/mse2024-be:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      -"FOO": "bar"
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:

